### ISSUE TITLE
Ignore topology errors when executing ssn_assmble function

### ISSUE THREAD

**Issue by HajimeSeya** [pet221/SSNbler#2]
Thank you for sharing this great package. I am trying to understand if this package can be used for sewer network data. Sewer networks have complex confluences that do not occur in river network data, so when I run ssn_assmble, I get a "Topological error: more than two edges flowing into this confluence" error message will be displayed. Is it possible to ignore this message and proceed with the process?

**Comment by michaeldumelle** [comment]
Hi @HajimeSeya thanks for reaching out, and we really appreciate the kind words about the package! We are hoping to submit `SSNbler` to CRAN in the next few months. Currently, `SSNbler` does not support networks that have complex confluences. We recognize that it may not make sense to resolve complex confluences in a sewer network, so this is a (current) limitation of the software for your work.

More information about the theory behind the geoprocessing tools is provided [at this link](https://www.jstatsoft.org/article/view/v056i02).

I am closing this issue but feel free to respond to the thread if you have any additional questions or would like any additional clarifications.
